# [source]
# type = "N2N"
# address = "127.0.0.1:3001"
# min_depth = 10

[source]
type = "N2C"
path = "/tmp/node.socket"
min_depth = 10

# [source]
# type = "UTXORPC"
# address = "https://64.176.196.20:50051"

[enrich]
type = "Sled"
db_path = "/data/era/sled_db"
consumed_ring_path = "/data/era/all_consumed"

[blocks]
db_path = "/data/era/block_buffer"
rollback_db_path = "/data/era/rollback_buffer"

[storage]
type = "Redis"
connection_params = "redis://127.0.0.1:6379/0"
cursor_key = "_cursor"

[[reducers]]
type = "Utxo"
key_prefix = "tx"
coin_key_prefix = "c"
datum_key_prefix = "d"

[[reducers]]
type = "Metadata"
projection = "Json"
key_prefix = "m"
royalty_key_prefix = "m.r"

[[reducers]]
type = "AssetsBalances"

[[reducers]]
type = "Handles"
key_prefix = "h"
policy_id = "f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a"

[[reducers]]
type = "AssetsLastMoved"
key_prefix = "p"

[[reducers]]
type = "Parameters"
key_prefix = "pr"

[[reducers]]
type = "StakeToPool"
key_prefix = "pl"

[intersect]
type = "Origin"

[policy]
missing_data = "Skip"
